### ISSUE TITLE
Not quite builable with instructions

### ISSUE THREAD

**Issue by rkiddy** [votinginfoproject/android-white-label-app#84]
This is an amazing job. It is usually much harder to build these kinds of apps, but most of it worked. And it even launched. Great job!

That being said, there were a few issues:

Error:Execution failed for task ':app:mergeDebugResources'.
> Unsupported type 'screenName' in file /home/ray/Projects/Voting/android-white-label-app/app/src/main/res/values/app_tracker.xml

I went in to the app_tracker.xml and commented there out. Then the next thing gave an error and then the next and so on.

I ended up just commenting out the bit that registers the tracking and then the two calls that invoke that. And then it worked fine.

Any suggestions? If there is other info I can supply, please let me know.

I am on Ubuntu 14.04LTS. I am running Android 1.3.2 and have Lollipop SDKs installed.

By the way, the SDK Manager does not look as you describe it. For one thing, I do not see "Extras" anywhere.

**Comment by flibbertigibbet** [comment]
The `app_tracker.xml` file goes in the `xml` directory, not the `values` directory. (The `api_keys.xml` file does go in the `values` directory.)

The SDK Manager interface has changed since this project was put together. Click to 'Launch Standalone SDK Manager' and you'll get the old interface with the 'Extras' subsection.
